### ISSUE TITLE
Provider for procps should be systemd for Ubuntu >= 15.04

### ISSUE THREAD

**Issue by jrosenboom** [svanzoest-cookbooks/sysctl#22]
Currently Upstart is chosen for Ubuntu >= 9.10, this will fail for Vivid.

**Comment by fletchowns** [comment]
https://github.com/svanzoest-cookbooks/sysctl/commit/f30356483b61e075be97984b6d5dbbe0377ef57f appears to have added support for Ubuntu 15.04 (systemd) but it's failing for me because it's still trying to use upstart.

@Koscomo any ideas?
