### ISSUE TITLE
procps failure on rhel 6.5

### ISSUE THREAD

**Issue by sergiopatino** [svanzoest-cookbooks/sysctl#27]
Restarting procps service triggered by sysctl:apply defined within this cookbook is generating the below error on my Red Hat 6.5 box. 

Output:
--------------------------------------
    Recipe: sysctl::service
    service[procps] action start

    Error executing action `start` on resource 'service[procps]'
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/service procps start ----
    STDOUT:
    STDERR:
    ---- End output of /sbin/service procps start ----
    Ran /sbin/service procps start returned 1

 Resource Declaration:
 ---------------------
    In /var/chef/cache/cookbooks/sysctl/recipes/service.rb
     26: service 'procps' do
     27:   supports :restart => true, :reload => true, :status => false
     28:   case node['platform']
     29:   when 'freebsd'
     30:     service_name 'sysctl'
     31:   when 'arch', 'exherbo'
     32:     service_name 'systemd-sysctl'
     33:     provider Chef::Provider::Service::Systemd
     34:   when 'ubuntu'
     35:     if node['platform_version'].to_f >= 9.10
     36:       service_name 'procps-instance' if node['platform_version'].to_f >= 14.10
     37:       provider Chef::Provider::Service::Upstart
     38:     end
     39:   end

Compiled Resource:
 ------------------
    Declared in /var/chef/cache/cookbooks/sysctl/recipes/service.rb:26:in `from_file'

    service("procps") do
      action [:enable]
      updated true
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "procps"
      enabled true
      pattern "procps"
      declared_type :service
      cookbook_name "sysctl"
      recipe_name "service"
    end

Contents of /etc/rc.d/init.d/functions:
 ------------------
    Apply sysctl settings, including files in /etc/sysctl.d 
    apply_sysctl() {
    sysctl -e -p /etc/sysctl.conf >/dev/null 2>&1
    for file in /etc/sysctl.d/* ; do
        is_ignored_file "$file" && continue
        test -f "$file" && sysctl -e -p "$file" >/dev/null 2>&1
     done
     }

**Comment by sergiopatino** [comment]
Anyone else on RHEL 6 who can confirm this issue?

**Comment by sergiopatino** [comment]
This issue appears to be with 

for file in /etc/sysctl.d/* ; do
    is_ignored_file "$file" && continue
    test -f "$file" && sysctl -e -p "$file" >/dev/null 2>&1
 done

If /etc/sysctl.d/ directory is empty this function will return 1 instead of 0.

**Comment by ericmhalvorsen** [comment]
Nice find. I am seeing this issue as well. Currently on Oracle Linux 6.5 though.

**Comment by svanzoest** [comment]
In most cases we would create a file in `/etc/sysctl.d/` with the parameters to load, so in most cases it would not be empty. Are you setting `node['sysctl']['allow_sysctl_conf']` to `true`?

**Comment by svanzoest** [comment]
any more thoughts on this before I close the issue?

**Comment by sergiopatino** [comment]
we can close this. I have a cookbook that manages /etc/sysctl.conf with a vanilla config (allow_sysctl_conf is set to false) and then we have cookbooks that add customizations in /etc/sysctl.d/
