### ISSUE TITLE
Integer values are rendered as floats

### ISSUE THREAD

**Issue by michaelklishin** [svanzoest-cookbooks/sysctl#28]
I've noticed that when I have

```
"file-max": "5000000"
```

in node attributes, it is rendered as `300000.0` and ignored by `sysctl`.

Changing it to

````
"file-max": "5000000"
```

makes things work as expected. Needless to say, this is confusing and violates the principle of least surprise ;)

**Comment by drpebcak** [comment]
These look exactly the same?

**Comment by martinb3** [comment]
Indeed, was one of those code sections supposed to be different @michaelklishin?
