### ISSUE TITLE
The cookbook works on archlinux, too, if you include it in the platform_family check

### ISSUE THREAD

**Issue by evaryont** [svanzoest-cookbooks/sysctl#29]
As the title says. If you add 'arch_linux' to [the platform_family check](https://github.com/svanzoest-cookbooks/sysctl/blob/master/attributes/default.rb#L29), the rest of the cookbook will work.

In the mean time, a work around is to specify the attributes in your own cookbook:

```ruby
if node['platform'] == 'arch'
  node.default['sysctl']['conf_dir'] = '/etc/sysctl.d'
  node.default['sysctl']['conf_file'] = File.join(node['sysctl']['conf_dir'], '/99-chef-attributes.conf')
end
```

**Comment by flaccid** [comment]
@svanzoest express merge please :)

**Comment by drpebcak** [comment]
Merged!
