### ISSUE TITLE
Suse 11 & 12 Support

### ISSUE THREAD

**Issue by joerocklin** [svanzoest-cookbooks/sysctl#32]
I'm working through all of the tests to make sure nothing is broken on the other platforms, and while that's going on I realized that I can't check in the kitchen.yml pointing to our Suse images. Do you have any preference on how to handle supporting a platform that doesn't have publicly available images?

**Comment by svanzoest** [comment]
If there are no public images then there is no way we can make it part of our test suite, so we will not be able to ensure compatibility going forward. We can definitely add support, but it will not be official.
