### ISSUE TITLE
ruby_block[save-sysctl-params] not found

### ISSUE THREAD

**Issue by tjj9020** [svanzoest-cookbooks/sysctl#51]
As of 0.7.4 the following message now occurs when using the cookbook:

` resource execute[sysctl[net.core.somaxconn]] is configured to notify resource ruby_block[save-sysctl-params] with action run, but ruby_block[save-sysctl-params] cannot be found in the resource collection. execute[sysctl[net.core.somaxconn]] is defined in /tmp/kitchen/cookbooks/sysctl/providers/param.rb:23:in `block in class_from_file'
`

**Comment by erulabs** [comment]
Note: Rolling back to 0.7.0 resolves the issue

**Comment by tjj9020** [comment]
0.7.2 seemed to work as well

**Comment by phs** [comment]
It appears to be brought in by efcfa4a, which declares `use_inline_resources`.  As described [here](http://blog.backslasher.net/chef-inline.html):
> You cannot subscribe to / notify resources that are not part of this resource's context.

**Comment by svanzoest** [comment]
I am surprised the tests did not catch this.

**Comment by svanzoest** [comment]
Also see
http://jtimberman.housepub.org/blog/2015/01/17/quick-tip-define-resources-to-notifiy-in-lwrps/

**Comment by TD-4242** [comment]
rspec test doesn't seem to catch it but kitchen will not converge.

**Comment by TD-4242** [comment]
Looks like chefspec is just matching that the notify exists in the resource but doesn't verify that what it is notifying is in the correct context.

**Comment by svanzoest** [comment]
I have reverted https://github.com/svanzoest-cookbooks/sysctl/commit/efcfa4adaf219720f6eb959849e336a5293fd3e3 and released v0.7.5. I created #54 to address this longer term. PRs are welcome.
