### ISSUE TITLE
FreeBSD support?

### ISSUE THREAD

**Issue by sekrett** [svanzoest-cookbooks/sysctl#55]
Hi there, excellent cookbook. But why don't you announce it is compatible with FreeBSD? You have implemented the code, I checked on version 10.2, values are changed and persisted after reboot, for me no problems. Do you know any issues with that?

**Comment by svanzoest** [comment]
we do not test FreeBSD a lot and only recently added 10.3 in test kitchen. It is great to hear that it works for you. I am not aware of any issues, but I haven't used or tested it much on FreeBSD.

**Comment by svanzoest** [comment]
I added it to the README of 0.8.0
