### ISSUE TITLE
cookbook dependancies in the metadata

### ISSUE THREAD

**Issue by Stromweld** [svanzoest-cookbooks/sysctl#63]
cookbook dependencies should specify minimum version instead of approximate version(>= instead of ~>). This allows dependencies to be upgraded to latest version, with bug fixes and enhancements, even if major version changes without update of this cookbook. If breaking change is found then pinning to specifc version makes more sense and should be noted in changelog and or readme.

**Comment by svanzoest** [comment]
A major semver change suggests there is a breaking change, therefore we
need to test that and do a release if it passes. This is a rare occurrence
as we only depend on ohai.

I think it is more important to not break users of the cookbook than
supporting the latest veraion of ohai.

**Comment by Stromweld** [comment]
Major version does not suggest breaking changes, although that is possible too, but more so suggests new features or major rework to make things more efficient while still maintaining same functionality and outcome.

I've been running into issues lately where berks figures out all the dependancies and one cookbook may cause others to not be on the latest with the latest bug fixes and we either run into errors(that have been fixed in latest version) during chef client runs, or we are not able to take advantage of some of the newer resources. Especially on cookbooks that are pretty well written and don't need much maintenance they tend to go stagnant and are arbitrarily holding other cookbooks version back. 

This has been more prevalent on the windows side as resources have been moved from windows cookbook to chef natively and windows cookbook was forever on 1.x and is now on 2.0.2 and removes a lot of deprecation warnings etc...

**Comment by svanzoest** [comment]
On Sep 15, 2016 8:14 AM, "Corey Hemminger" <notifications@github.com> wrote:
>
> Major version does not suggest breaking changes, although that is
possible too, but more so suggests new features or major rework to make
things more efficient while still maintaining same functionality and
outcome.

Please read http://semver.org

> I've been running into issues lately where berks figures out all the
dependancies and one cookbook may cause others to not be on the latest with
the latest bug fixes and we either run into errors(that have been fixed in
latest version) during chef client runs, or we are not able to take
advantage of some of the newer resources. Especially on cookbooks that are
pretty well written and don't need much maintenance they tend to go
stagnant and are arbitrarily holding other cookbooks version back.

That is an issue of lack of maintenance, not an issue with version
dependencies. A Major update implies unknown compatibility from a dependent
cookbook point of view and requires confirmation and changes to support the
new version.

-- Sander

**Comment by Stromweld** [comment]
Semver isn't always followed to a T. Case in point this cookbook according to 4 and 5 directives below means that this cookbook is still in initial development and shouldn't be used in production. If it is production ready it should of been bumped to 1.0 regardless if there is not breaking changes from 0.x versions.

4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

5. Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.
 
Taken from their FAQ: 
How do I know when to release 1.0.0?

If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.


Breaking changes also doesn't mean it breaks your cookbook either, you may not be using any of the breaking changes. If so then pinning to a specific major version makes sense till a fix can be made and dependency updated. But if ohai 5.x comes out I have to wait on your cookbook, and anyone else's cookbooks I'm using, who has a dependency set on it and specifying version. This could take days, weeks, or months. Tracking down cookbook that's forcing me to older versions is not easy either.

In my opinion dependencies should set minimum version only unless a breaking change is found in a specific version for community cookbooks. That way users can use newer cookbooks and restrict maximum version of a cookbook as they deem necessary for their code.

**Comment by Stromweld** [comment]
I hope I'm not coming off combative and please don't take offense to my comments. I am definitely not trying to offend here.

 I'm mainly opened this issue because we like to stay up to date on chef-client and cookbooks and I've been starting to run into issues where we want to use a newer version of a cookbook that may have just came out. Due to dependencies of dependencies berks ends up installing wrong version of a cookbook. In a couple of cases when we put in a hard dependency to the latest version it then downgraded a different cookbook that didn't allow the latest and it got downgraded to a really old version that didn't have the version defined in the dependency. Which then broke other things for us since that cookbook went from 1.0.3 to 0.1.0 and didn't have the functionality we were using.

Once they updated the metadata on the community cookbook to specify minimum version instead of approximate version then everything worked out fine and berks was able to reconcile latest packages. I started to see if I can get other community cookbooks that we use to do the same so that I can have better control over the max version and avoid these breakages in the future.

**Comment by svanzoest** [comment]
You should be able to update to any `ohai` in the 4.X range, however, since nothing currently in the later releases is breaking anything, I am going to open this up to >= 4.0 as you suggest, however, I fear we wll break when 5.0 comes out.

**Comment by Stromweld** [comment]
I understand that. In the end ohai was developed to do meet a specific need so any changes shouldn't break it's primary functional use. With that though different parts can change on how they meet the end goal of the ohai cookbook and if that breaks anything in this cookbook then at that time it does make sense to restrict version to the last working prior version until this cookbook can be updated to work with newer versions.

**Comment by Stromweld** [comment]
Thanks for the merge.
